[openSUSE] Basetools: Ignore spurious GCC 12 warning
References: bsc#1197018

Building with GCC 12 fails producing errors. This is an example (but
there are others):

[ 1051s] Sdk/C/LzmaEnc.c: In function 'LzmaEnc_CodeOneMemBlock':
[ 1051s] Sdk/C/LzmaEnc.c:2641:19: error: storing the address of local
variable 'outStream' in '*p.rc.outStream' [-Werror=dangling-pointer=]
[ 1051s]  2641 |   p->rc.outStream = &outStream.vt;
[ 1051s]       |   ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
[ 1051s] Sdk/C/LzmaEnc.c:2624:28: note: 'outStream' declared here
[ 1051s]  2624 |   CLzmaEnc_SeqOutStreamBuf outStream;
[ 1051s]       |                            ^~~~~~~~~
[ 1051s] Sdk/C/LzmaEnc.c:2624:28: note: 'pp' declared here

Which is a false positive reported by GCC compiler:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=98503

Work it around by silencing the warning.

Signed-off-by: Martin Liška <martin.liska@suse.com>
Signed-off-by: Dario Faggioli <dfaggioli@suse.com>